appid = "APPID"
secret = "SECRET"
token = "TOKEN"
host = "HOST"
template_id = "TEMPLATE_ID"
db_path = "db"
# 自定义内容展示模板，会替换{::}为具体内容
detail_template = "template.html"
# 内容过期时间，单位天。0表示不过期
content_expire = 1
# 监听地址
listen = "0.0.0.0:8800"
# 订阅公众号的欢迎消息
welcome = '''欢迎使用server碳消息推送系统。点击 <a href="weixin://bizmsgmenu?msgmenucontent=help&msgmenuid=100">help</a> 查看帮助信息'''
help = '''
创建频道 create channel 频道名
查看频道 <a href="weixin://bizmsgmenu?msgmenucontent=show%20channel&msgmenuid=101">show channel</a>
删除频道 del channel 频道id 
订阅频道 subscribe 频道id
取消订阅 unsubscribe 频道id 
查看订阅的频道 <a href="weixin://bizmsgmenu?msgmenucontent=show%20subscribe&msgmenuid=102">show subscribe</a>
'''
