name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      RELEASE_PATH: target/release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      if: matrix.os != 'windows-latest'
      run: |
        cargo build --release --verbose
        echo "::set-env name=RELEASE_FILE::${{env.RELEASE_PATH}}/server_tan_{{matrix.os}}"
        mv ${{env.RELEASE_PATH}}/server_tan ${{env.RELEASE_FILE }}
    - name: Build-Windows
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cargo build --release --verbose
        echo "::set-env name=RELEASE_FILE::${{env.RELEASE_PATH}}/server_tan_{{matrix.os}}.exe"
        mv ${{env.RELEASE_PATH}}/server_tan.exe ${{env.RELEASE_FILE }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{env.RELEASE_FILE}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
